// Realistic Lagos rental listings sourced from jiji.ng market data (June 2026)
export interface Listing {
  id: string
  title: string
  type: "apartment" | "duplex" | "mini_flat" | "bungalow" | "studio" | "shortlet" | "room_parlour" | "block_of_flats" | "land" | "office" | "shop"
  bedrooms: number
  bathrooms: number
  price: number
  pricePeriod: "yearly" | "monthly" | "weekly" | "daily"
  currency: "NGN"
  location: string
  area: string
  city: string
  description: string
  amenities: string[]
  images: string[]
  verified: boolean
  featured: boolean
  agent: string
  phone: string
  datePosted: string
  source: "jiji.ng"
  furnishing: "furnished" | "unfurnished" | "semi_furnished"
  condition: "new" | "fairly_used" | "renovated"
  serviceCharge?: number
}

export const AREA_NEIGHBORHOODS: Record<string, string[]> = {
  "Lekki": ["Ikota", "Chevron", "Agungi", "Ikate", "Lekki Phase 1", "Lekki Phase 2", "Osapa London", "Jakande"],
  "Ajah": ["Sangotedo", "Abraham Adesanya", "Awoyaya", "Oribanwa", "Eleko Junction", "Bogije", "Ibeju-Lekki"],
  "Victoria Island": ["Ademola Adetokunbo", "Adeola Odeku", "Karimu Kotun", "Bourdillon"],
  "Ikoyi": ["Old Ikoyi", "New Ikoyi", "Park View Estate", "Ikoyi Boulevard"],
  "Ikeja": ["Computer Village", "Ogba", "Omole Phase 2", "Mangoro", "Airport Road", "Alausa", "Secretariat"],
  "Surulere": ["Adeniran Ogunsanya", "Ogunlana Drive", "Bode Thomas", "Ijesha"],
  "Yaba": ["Herbert Macaulay", "Sabo", "Ebute Metta"],
  "Ikorodu": ["Ikorodu Garage", "Owode-Onirin", "Igbogbo", "Beyonce/Kings Estate"],
  "Ipaja": ["Ipaja Town", "Ayobo", "Agbado", "Boys Town"],
  "Satellite Town": ["Nasco Estate", "Abule Ado", "Festac Link Bridge"],
  "Epe": ["Epe Town", "Ajah Extension", "Bogije"],
  "Badagry": ["Badagry Town", "Iworo", "Aradagun"],
}

export const SEED_LISTINGS: Listing[] = [
  {
    id: "rn-001",
    title: "2-Bedroom Apartment in Ikota Estate",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 3500000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Ikota, Lekki",
    area: "Ikota",
    city: "Lagos",
    description: "Spacious 2-bedroom apartment in a serene and secure estate in Ikota, Lekki. Features POP ceiling, modern kitchen, 24-hour power supply, and ample parking. Close to Novare Mall and Shoprite.",
    amenities: ["24/7 Power", "Parking", "Security", "Water Supply", "POP Ceiling", "Modern Kitchen"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 801 234 5678",
    datePosted: "2026-06-15",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
  },
  {
    id: "rn-002",
    title: "Furnished 2-Bedroom Apartment in Lekki",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 900000,
    pricePeriod: "monthly",
    currency: "NGN",
    location: "Lekki Phase 1",
    area: "Lekki Phase 1",
    city: "Lagos",
    description: "Fully furnished 2-bedroom apartment available for monthly rental in the heart of Lekki Phase 1. Features: smart TV, washing machine, fully equipped kitchen, AC in all rooms. Ideal for expatriates and short-term stays.",
    amenities: ["Furnished", "Smart TV", "Washing Machine", "AC", "Generator", "Gated Estate", "Swimming Pool"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 802 345 6789",
    datePosted: "2026-06-20",
    source: "jiji.ng",
    furnishing: "furnished",
    condition: "new",
  },
  {
    id: "rn-003",
    title: "3-Bedroom Duplex in Ikate Elegushi",
    type: "duplex",
    bedrooms: 3,
    bathrooms: 4,
    price: 30000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Ikate, Lekki",
    area: "Ikate",
    city: "Lagos",
    description: "Tastefully furnished 3-bedroom terrace duplex in a serene and secured estate. Features BQ, private garden, 2 car garage, 100KVA generator, and CCTV surveillance. Premium neighborhood.",
    amenities: ["BQ", "Private Garden", "2 Car Garage", "100KVA Generator", "CCTV", "Swimming Pool", "Gym"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 803 456 7890",
    datePosted: "2026-06-10",
    source: "jiji.ng",
    furnishing: "furnished",
    condition: "new",
  },
  {
    id: "rn-004",
    title: "2-Bedroom Flat in Oribanwa Phase 2",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 2500000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Oribanwa, Ajah",
    area: "Oribanwa",
    city: "Lagos",
    description: "Newly built 2-bedroom flat in Oribanwa Phase 2, Ajah. Spacious rooms with en-suite bathrooms, POP ceiling, and tiled floors. Close to Abraham Adesanya estate. Agency fee 10%.",
    amenities: ["Water Supply", "POP Ceiling", "Tiled Floors", "En-suite", "Parking"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 804 567 8901",
    datePosted: "2026-06-18",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
    serviceCharge: 250000,
  },
  {
    id: "rn-005",
    title: "3-Bedroom Apartment in Computer Village",
    type: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    price: 3500000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Computer Village, Ikeja",
    area: "Computer Village",
    city: "Lagos",
    description: "3-bedroom flat at Seriki Aro, Ikeja, close to Ikeja under bridge. Spacious living room, modern kitchen, and all rooms en-suite. Popular commercial area with easy access to BRT.",
    amenities: ["En-suite", "Modern Kitchen", "Spacious Living Room", "BRT Access", "Commercial Hub"],
    images: [],
    verified: false,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 805 678 9012",
    datePosted: "2026-06-12",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-006",
    title: "2-Bedroom Apartment in Solomade Estate",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 2500000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Ikorodu Garage, Ikorodu",
    area: "Ikorodu",
    city: "Lagos",
    description: "Newly built 2-bedroom fully en-suite apartment at Solomade Estate, Ikorodu Garage. Features POP ceiling, modern fittings, and ample parking. Growing neighborhood with good road network.",
    amenities: ["POP Ceiling", "En-suite", "Parking", "Water Supply", "Estate Security"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 806 789 0123",
    datePosted: "2026-06-08",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
  },
  {
    id: "rn-007",
    title: "2-Bedroom Flat with BQ in Agungi",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 3,
    price: 8000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Agungi, Lekki",
    area: "Agungi",
    city: "Lagos",
    description: "Brand new 2-bedroom apartment with BQ for rent at Oba Amusa Estate, Agungi. Premium finishes, spacious rooms, and modern kitchen. Located in one of Lekki's most sought-after neighborhoods.",
    amenities: ["BQ", "Modern Kitchen", "Premium Finishes", "Gated Estate", "24/7 Security", "Parking"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 807 890 1234",
    datePosted: "2026-06-22",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
    serviceCharge: 500000,
  },
  {
    id: "rn-008",
    title: "1-Bedroom Mini Flat in Sangotedo",
    type: "mini_flat",
    bedrooms: 1,
    bathrooms: 1,
    price: 800000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Sangotedo, Ajah",
    area: "Sangotedo",
    city: "Lagos",
    description: "Affordable 1-bedroom mini flat in Sangotedo, Ajah. Perfect for young professionals. Close to Novare Mall and major bus stops. Clean and well-maintained building.",
    amenities: ["Water Supply", "Parking", "Near Mall", "Bus Stop Access"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 808 901 2345",
    datePosted: "2026-06-14",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-009",
    title: "2-Bedroom Block of Flats in Ademola Adetokunbo",
    type: "block_of_flats",
    bedrooms: 2,
    bathrooms: 3,
    price: 25000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Ademola Adetokunbo, Victoria Island",
    area: "Ademola Adetokunbo",
    city: "Lagos",
    description: "Premium 2-bedroom flat with room BQ in the heart of Victoria Island. Located on one of Lagos' most prestigious streets. Perfect for corporate tenants and expatriates.",
    amenities: ["BQ", "Corporate Location", "24/7 Power", "High-Rise Building", "Concierge", "Underground Parking"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 809 012 3456",
    datePosted: "2026-06-05",
    source: "jiji.ng",
    furnishing: "semi_furnished",
    condition: "new",
    serviceCharge: 2000000,
  },
  {
    id: "rn-010",
    title: "1-Bedroom Apartment in Ajah",
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    price: 450000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Abraham Adesanya, Ajah",
    area: "Abraham Adesanya",
    city: "Lagos",
    description: "Affordable 1-bedroom apartment near Abraham Adesanya estate. Suitable for singles or young couples. Good road network and close to markets.",
    amenities: ["Water Supply", "Near Market", "Good Road", "Parking"],
    images: [],
    verified: false,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 810 123 4567",
    datePosted: "2026-06-19",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-011",
    title: "3-Bedroom House in Ajangbadi",
    type: "bungalow",
    bedrooms: 3,
    bathrooms: 3,
    price: 1000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Ajangbadi, Ojo",
    area: "Ajangbadi",
    city: "Lagos",
    description: "Fairly used 3-bedroom house in Ajangbadi. You will be the second tenant since built 4 years ago. Spacious compound with good neighborhood. Affordable option for families.",
    amenities: ["Spacious Compound", "Family-Friendly", "Quiet Neighborhood", "Water Supply"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 811 234 5678",
    datePosted: "2026-06-11",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-012",
    title: "Shortlet 2-Bedroom Apartment in Lekki",
    type: "shortlet",
    bedrooms: 2,
    bathrooms: 2,
    price: 500000,
    pricePeriod: "weekly",
    currency: "NGN",
    location: "Lekki Phase 1",
    area: "Lekki Phase 1",
    city: "Lagos",
    description: "Luxury 2-bedroom shortlet apartment in Lekki Phase 1. Fully furnished with premium amenities. Perfect for weekend getaways, business trips, or short-term stays. 2 persons can share rent.",
    amenities: ["Fully Furnished", "Smart TV", "WiFi", "Air Conditioning", "Washing Machine", "Kitchen", "Pool Access"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 812 345 6789",
    datePosted: "2026-06-21",
    source: "jiji.ng",
    furnishing: "furnished",
    condition: "new",
  },
  {
    id: "rn-013",
    title: "3-Bedroom Apartment in Omole Phase 2",
    type: "block_of_flats",
    bedrooms: 3,
    bathrooms: 3,
    price: 3000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Omole Phase 2, Ikeja",
    area: "Omole Phase 2",
    city: "Lagos",
    description: "Executive 3-bedroom apartment at Omole Extension. Spacious living area, modern kitchen, and all rooms en-suite. Quiet residential neighborhood close to Oba Akran Avenue.",
    amenities: ["En-suite", "Modern Kitchen", "Quiet Area", "Parking", "Estate Security"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 813 456 7890",
    datePosted: "2026-06-17",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-014",
    title: "Studio Apartment in Yaba",
    type: "studio",
    bedrooms: 0,
    bathrooms: 1,
    price: 350000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Herbert Macaulay, Yaba",
    area: "Herbert Macaulay",
    city: "Lagos",
    description: "Compact studio apartment on Herbert Macaulay Way, Yaba. Ideal for students and young professionals. Close to University of Lagos and major tech hubs. Easy access to mainland attractions.",
    amenities: ["Compact Living", "Near UNILAG", "Tech Hub Access", "Public Transport"],
    images: [],
    verified: false,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 814 567 8901",
    datePosted: "2026-06-16",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-015",
    title: "2-Bedroom Apartment in Satellite Town",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 3000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Satellite Town, Amuwo-Odofin",
    area: "Satellite Town",
    city: "Lagos",
    description: "2-bedroom apartment located at Red Gate, newly built and very spacious. Not far from bus stop. Close to Festac and Trade Fair Complex.",
    amenities: ["New Build", "Spacious", "Near Bus Stop", "Close to Festac"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 815 678 9012",
    datePosted: "2026-06-09",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
  },
  {
    id: "rn-016",
    title: "2-Bedroom Apartment with Solar in Nasco Estate",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 3500000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Nasco Estate, Satellite Town",
    area: "Satellite Town",
    city: "Lagos",
    description: "Standard 2-bedroom apartment with 15KW solar panel in Nasco Estate. You buy your own battery. Very spacious and well-ventilated. Good for families who want reliable power.",
    amenities: ["15KW Solar", "Spacious", "Good Ventilation", "Estate Security", "Water Supply"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 816 789 0123",
    datePosted: "2026-06-07",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
  },
  {
    id: "rn-017",
    title: "2-Bedroom Flat in Mercyland Estate",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 2000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Ipaja, Lagos",
    area: "Ipaja Town",
    city: "Lagos",
    description: "Newly built 2-bedroom flat at Mercyland Estate, Ipaja. Clean environment with good road access. Affordable option for families on the mainland.",
    amenities: ["New Build", "Estate", "Good Road Access", "Water Supply"],
    images: [],
    verified: false,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 817 890 1234",
    datePosted: "2026-06-13",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
  },
  {
    id: "rn-018",
    title: "1-Bedroom Apartment in Epe",
    type: "mini_flat",
    bedrooms: 1,
    bathrooms: 1,
    price: 1200000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Epe, Lagos",
    area: "Epe Town",
    city: "Lagos",
    description: "Two bedroom and mini flat in Epe. Good for two people sharing. Quiet suburban area with growing infrastructure. Close to Epe Fish Market and Lagoon.",
    amenities: ["Quiet Area", "Growing Infrastructure", "Near Market", "Suburban"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 818 901 2345",
    datePosted: "2026-06-06",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "fairly_used",
  },
  {
    id: "rn-019",
    title: "2-Bedroom Terrace in Lekki Phase 1",
    type: "duplex",
    bedrooms: 2,
    bathrooms: 3,
    price: 12000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Lekki Phase 1",
    area: "Lekki Phase 1",
    city: "Lagos",
    description: "Newly built serviced 2-bedroom terrace in Lekki Phase 1. A unit just became available. Premium finishes, smart home features, and dedicated parking. Top-tier security.",
    amenities: ["Serviced", "Smart Home", "Dedicated Parking", "Top Security", "Modern Design", "BQ"],
    images: [],
    verified: true,
    featured: true,
    agent: "RentNaija Verified",
    phone: "+234 819 012 3456",
    datePosted: "2026-06-23",
    source: "jiji.ng",
    furnishing: "semi_furnished",
    condition: "new",
    serviceCharge: 1000000,
  },
  {
    id: "rn-020",
    title: "2-Bedroom Apartment in Chevron",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    price: 9000000,
    pricePeriod: "yearly",
    currency: "NGN",
    location: "Chevron, Lekki",
    area: "Chevron",
    city: "Lagos",
    description: "2-Bedroom Apartment at New Road, Lekki Axis. Located in a peaceful and well-maintained estate with 24-hour security and power backup. Close to Chevron Estate and Lekki Free Trade Zone.",
    amenities: ["24/7 Security", "Power Backup", "Gated Estate", "Water Supply", "Parking", "Near Free Trade Zone"],
    images: [],
    verified: true,
    featured: false,
    agent: "RentNaija Verified",
    phone: "+234 820 123 4567",
    datePosted: "2026-06-04",
    source: "jiji.ng",
    furnishing: "unfurnished",
    condition: "new",
  },
]

export function formatPrice(price: number): string {
  return `₦${price.toLocaleString()}`
}

export function formatPriceWithPeriod(price: number, period: string): string {
  const suffix = period === "yearly" ? "/yr" : period === "monthly" ? "/mo" : period === "weekly" ? "/wk" : "/day"
  return `₦${price.toLocaleString()}${suffix}`
}

export function getTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    apartment: "Apartment",
    duplex: "Duplex",
    mini_flat: "Mini Flat",
    bungalow: "Bungalow",
    studio: "Studio",
    shortlet: "Shortlet",
    room_parlour: "Room & Parlour",
    block_of_flats: "Block of Flats",
    land: "Land",
    office: "Office",
    shop: "Shop",
  }
  return labels[type] || type
}
